project:
  type: website
  output-dir: _site

website:
  title: "Julien Emile-Geay"
  description: "Paleoclimatology, Climate Dynamics, Data Science, Open Knowledge"
  site-url: https://climdyn.usc.edu
  repo-url: https://github.com/CommonClimate/climdyn
  favicon: assets/favicon.ico
  
  navbar:
    tools:
    - icon: github
      href: https://www.github.com/CommonClimate/climdyn-quarto
    right:
      - text: Research
        aria-label: "Research Projects"
        href: projects.qmd
      - text: Publications
        aria-label: "Publications"
        href: publications.qmd
      - text: Teaching
        aria-label: "Teaching"
        href: teaching.qmd
      - text: Life
        aria-label: "Life outside the lab"
        href: life.qmd
      - text: News
        aria-label: "News and Updates"
        href: blog.qmd
      

  page-footer:
    left: |
      Â© 2026 Julien Emile-Geay. Built with [Quarto](https://quarto.org) using 
    right:
      - icon: twitter
        href: https://twitter.com/StellarGeay
        aria-label: Twitter
      - icon: github
        href: https://github.com/CommonClimate
        aria-label: GitHub
      - icon: envelope
        href: mailto:julieneg@usc.edu
        aria-label: Email

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/theme-light.scss
      dark: 
        - cosmo
        - assets/theme-dark.scss
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

bibliography: references.bib
csl: agu.csl

execute:
  freeze: auto